### ISSUE TITLE
Maintaining this repository

### ISSUE THREAD

**Issue by TomHAnderson** [zfcampus/zf-doctrine-querybuilder#43]
It's been over a year since anything was merged into this repo.  Will someone please step up to maintain it?  I volunteer if nobody else is going to take the job.

**Comment by webimpress** [comment]
@TomHAnderson the problem is not in merging, the problem is in reviewing. I can merge but before I should get some approval from @zfcampus/doctrine team on PRs and it's going to be very hard...

**Comment by webimpress** [comment]
@TomHAnderson [1.6.0](https://github.com/zfcampus/zf-doctrine-querybuilder/releases/tag/1.6.0) is now released
