### ISSUE TITLE
Compatibility with DoctrineORMModule 2.1?

### ISSUE THREAD

**Issue by shandyDev** [zfcampus/zf-doctrine-querybuilder#45]
So, see topic.

**Comment by TomHAnderson** [comment]
I am in charge of DoctrineORMModule and I wrote this one.  What's your problem?

**Comment by shandyDev** [comment]
Look my PR. In general it issue between
- zf-apigility-doctrine (require phpro/zf-doctrine-hydration-module ^3.0)
- phpro/zf-doctrine-hydration-module (which require  DoctrineORMModule ^1.2) you have already https://github.com/phpro/zf-doctrine-hydration-module/pull/38 PR
And this module which again require  DoctrineORMModule ^1.2 in composer

**Comment by TomHAnderson** [comment]
Thanks @shandyDev your PR should be merged and a release made asap.

**Comment by TomHAnderson** [comment]
I do not have control over this repository but these two do: @weierophinney @webimpress
